### ISSUE TITLE
Feature #3 : Design Service Level page

### ISSUE THREAD

**Issue by sam13113** [arunkumarsa7/PortfolioManagerClient#5]
As user clicks on a OE in homepage. He/she should be redirected to this page.

1. All services provided by the OE should be listed here
2. Each service should be clickable icon

**Comment by arunkumarsa7** [comment]
1. As user clicks on a OE in homepage. He/she should be redirected to this page
2. All services provided by the OE should be listed here
3. Each service should be clickable icon
Currently these are hard coded values and making them dynamic will be done in next phase.
