### ISSUE TITLE
Feature #5 : Design Portfolio Dashboard

### ISSUE THREAD

**Issue by sam13113** [arunkumarsa7/PortfolioManagerClient#7]
As user clicks a portfolio. he/she is redirected to this page.

The page is built of three sub pages.

1. The top tiles view which groups all SLAs into three color coded tiles and a button group
2. A tabular representation of all teams under the portfolio
3. A graphical representation of SLAs

refer page 4 for reference

**Comment by arunkumarsa7** [comment]
Static rendering of the page is complete, making the page completely dynamic is pending and will be done is Sprint 2.
